/*
KubeSphere

Testing DevOpsScmAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/lee-doctor/kubesphere-sdk-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_DevOpsScmAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DevOpsScmAPIService CreateSCMServers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var scm string

		resp, httpRes, err := apiClient.DevOpsScmAPI.CreateSCMServers(context.Background(), scm).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DevOpsScmAPIService GetOrgRepo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var scm string
		var organization string

		resp, httpRes, err := apiClient.DevOpsScmAPI.GetOrgRepo(context.Background(), scm, organization).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DevOpsScmAPIService GetSCMOrg", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var scm string

		resp, httpRes, err := apiClient.DevOpsScmAPI.GetSCMOrg(context.Background(), scm).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DevOpsScmAPIService GetSCMServers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var scm string

		resp, httpRes, err := apiClient.DevOpsScmAPI.GetSCMServers(context.Background(), scm).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DevOpsScmAPIService Validate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var scm string

		resp, httpRes, err := apiClient.DevOpsScmAPI.Validate(context.Background(), scm).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
