/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OpenpitrixModifyCategoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenpitrixModifyCategoryRequest{}

// OpenpitrixModifyCategoryRequest struct for OpenpitrixModifyCategoryRequest
type OpenpitrixModifyCategoryRequest struct {
	Description *string `json:"description,omitempty"`
	Icon *string `json:"icon,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewOpenpitrixModifyCategoryRequest instantiates a new OpenpitrixModifyCategoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenpitrixModifyCategoryRequest() *OpenpitrixModifyCategoryRequest {
	this := OpenpitrixModifyCategoryRequest{}
	return &this
}

// NewOpenpitrixModifyCategoryRequestWithDefaults instantiates a new OpenpitrixModifyCategoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenpitrixModifyCategoryRequestWithDefaults() *OpenpitrixModifyCategoryRequest {
	this := OpenpitrixModifyCategoryRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OpenpitrixModifyCategoryRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenpitrixModifyCategoryRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OpenpitrixModifyCategoryRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OpenpitrixModifyCategoryRequest) SetDescription(v string) {
	o.Description = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *OpenpitrixModifyCategoryRequest) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenpitrixModifyCategoryRequest) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *OpenpitrixModifyCategoryRequest) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *OpenpitrixModifyCategoryRequest) SetIcon(v string) {
	o.Icon = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *OpenpitrixModifyCategoryRequest) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenpitrixModifyCategoryRequest) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *OpenpitrixModifyCategoryRequest) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *OpenpitrixModifyCategoryRequest) SetLocale(v string) {
	o.Locale = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OpenpitrixModifyCategoryRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenpitrixModifyCategoryRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OpenpitrixModifyCategoryRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OpenpitrixModifyCategoryRequest) SetName(v string) {
	o.Name = &v
}

func (o OpenpitrixModifyCategoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenpitrixModifyCategoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableOpenpitrixModifyCategoryRequest struct {
	value *OpenpitrixModifyCategoryRequest
	isSet bool
}

func (v NullableOpenpitrixModifyCategoryRequest) Get() *OpenpitrixModifyCategoryRequest {
	return v.value
}

func (v *NullableOpenpitrixModifyCategoryRequest) Set(val *OpenpitrixModifyCategoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenpitrixModifyCategoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenpitrixModifyCategoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenpitrixModifyCategoryRequest(val *OpenpitrixModifyCategoryRequest) *NullableOpenpitrixModifyCategoryRequest {
	return &NullableOpenpitrixModifyCategoryRequest{value: val, isSet: true}
}

func (v NullableOpenpitrixModifyCategoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenpitrixModifyCategoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


