/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1NodeSelector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1NodeSelector{}

// V1NodeSelector A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
type V1NodeSelector struct {
	// Required. A list of node selector terms. The terms are ORed.
	NodeSelectorTerms []V1NodeSelectorTerm `json:"nodeSelectorTerms"`
}

type _V1NodeSelector V1NodeSelector

// NewV1NodeSelector instantiates a new V1NodeSelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1NodeSelector(nodeSelectorTerms []V1NodeSelectorTerm) *V1NodeSelector {
	this := V1NodeSelector{}
	this.NodeSelectorTerms = nodeSelectorTerms
	return &this
}

// NewV1NodeSelectorWithDefaults instantiates a new V1NodeSelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1NodeSelectorWithDefaults() *V1NodeSelector {
	this := V1NodeSelector{}
	return &this
}

// GetNodeSelectorTerms returns the NodeSelectorTerms field value
func (o *V1NodeSelector) GetNodeSelectorTerms() []V1NodeSelectorTerm {
	if o == nil {
		var ret []V1NodeSelectorTerm
		return ret
	}

	return o.NodeSelectorTerms
}

// GetNodeSelectorTermsOk returns a tuple with the NodeSelectorTerms field value
// and a boolean to check if the value has been set.
func (o *V1NodeSelector) GetNodeSelectorTermsOk() ([]V1NodeSelectorTerm, bool) {
	if o == nil {
		return nil, false
	}
	return o.NodeSelectorTerms, true
}

// SetNodeSelectorTerms sets field value
func (o *V1NodeSelector) SetNodeSelectorTerms(v []V1NodeSelectorTerm) {
	o.NodeSelectorTerms = v
}

func (o V1NodeSelector) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1NodeSelector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodeSelectorTerms"] = o.NodeSelectorTerms
	return toSerialize, nil
}

func (o *V1NodeSelector) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nodeSelectorTerms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1NodeSelector := _V1NodeSelector{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1NodeSelector)

	if err != nil {
		return err
	}

	*o = V1NodeSelector(varV1NodeSelector)

	return err
}

type NullableV1NodeSelector struct {
	value *V1NodeSelector
	isSet bool
}

func (v NullableV1NodeSelector) Get() *V1NodeSelector {
	return v.value
}

func (v *NullableV1NodeSelector) Set(val *V1NodeSelector) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NodeSelector) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NodeSelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NodeSelector(val *V1NodeSelector) *NullableV1NodeSelector {
	return &NullableV1NodeSelector{value: val, isSet: true}
}

func (v NullableV1NodeSelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NodeSelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


