/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DevopsReplayPipelineCauses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DevopsReplayPipelineCauses{}

// DevopsReplayPipelineCauses struct for DevopsReplayPipelineCauses
type DevopsReplayPipelineCauses struct {
	// It’s a fully qualified name and is an identifier of the producer of this resource's capability.
	Class *string `json:"_class,omitempty"`
	// short description
	ShortDescription *string `json:"shortDescription,omitempty"`
	// user id
	UserId *string `json:"userId,omitempty"`
	// user name
	UserName *string `json:"userName,omitempty"`
}

// NewDevopsReplayPipelineCauses instantiates a new DevopsReplayPipelineCauses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDevopsReplayPipelineCauses() *DevopsReplayPipelineCauses {
	this := DevopsReplayPipelineCauses{}
	return &this
}

// NewDevopsReplayPipelineCausesWithDefaults instantiates a new DevopsReplayPipelineCauses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDevopsReplayPipelineCausesWithDefaults() *DevopsReplayPipelineCauses {
	this := DevopsReplayPipelineCauses{}
	return &this
}

// GetClass returns the Class field value if set, zero value otherwise.
func (o *DevopsReplayPipelineCauses) GetClass() string {
	if o == nil || IsNil(o.Class) {
		var ret string
		return ret
	}
	return *o.Class
}

// GetClassOk returns a tuple with the Class field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevopsReplayPipelineCauses) GetClassOk() (*string, bool) {
	if o == nil || IsNil(o.Class) {
		return nil, false
	}
	return o.Class, true
}

// HasClass returns a boolean if a field has been set.
func (o *DevopsReplayPipelineCauses) HasClass() bool {
	if o != nil && !IsNil(o.Class) {
		return true
	}

	return false
}

// SetClass gets a reference to the given string and assigns it to the Class field.
func (o *DevopsReplayPipelineCauses) SetClass(v string) {
	o.Class = &v
}

// GetShortDescription returns the ShortDescription field value if set, zero value otherwise.
func (o *DevopsReplayPipelineCauses) GetShortDescription() string {
	if o == nil || IsNil(o.ShortDescription) {
		var ret string
		return ret
	}
	return *o.ShortDescription
}

// GetShortDescriptionOk returns a tuple with the ShortDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevopsReplayPipelineCauses) GetShortDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ShortDescription) {
		return nil, false
	}
	return o.ShortDescription, true
}

// HasShortDescription returns a boolean if a field has been set.
func (o *DevopsReplayPipelineCauses) HasShortDescription() bool {
	if o != nil && !IsNil(o.ShortDescription) {
		return true
	}

	return false
}

// SetShortDescription gets a reference to the given string and assigns it to the ShortDescription field.
func (o *DevopsReplayPipelineCauses) SetShortDescription(v string) {
	o.ShortDescription = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *DevopsReplayPipelineCauses) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevopsReplayPipelineCauses) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *DevopsReplayPipelineCauses) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *DevopsReplayPipelineCauses) SetUserId(v string) {
	o.UserId = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *DevopsReplayPipelineCauses) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DevopsReplayPipelineCauses) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *DevopsReplayPipelineCauses) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *DevopsReplayPipelineCauses) SetUserName(v string) {
	o.UserName = &v
}

func (o DevopsReplayPipelineCauses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DevopsReplayPipelineCauses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Class) {
		toSerialize["_class"] = o.Class
	}
	if !IsNil(o.ShortDescription) {
		toSerialize["shortDescription"] = o.ShortDescription
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.UserName) {
		toSerialize["userName"] = o.UserName
	}
	return toSerialize, nil
}

type NullableDevopsReplayPipelineCauses struct {
	value *DevopsReplayPipelineCauses
	isSet bool
}

func (v NullableDevopsReplayPipelineCauses) Get() *DevopsReplayPipelineCauses {
	return v.value
}

func (v *NullableDevopsReplayPipelineCauses) Set(val *DevopsReplayPipelineCauses) {
	v.value = val
	v.isSet = true
}

func (v NullableDevopsReplayPipelineCauses) IsSet() bool {
	return v.isSet
}

func (v *NullableDevopsReplayPipelineCauses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevopsReplayPipelineCauses(val *DevopsReplayPipelineCauses) *NullableDevopsReplayPipelineCauses {
	return &NullableDevopsReplayPipelineCauses{value: val, isSet: true}
}

func (v NullableDevopsReplayPipelineCauses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevopsReplayPipelineCauses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


