/*
KS API

KubeSphere OpenAPI

API version: v4.1.1
Contact: support@kubesphere.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1PodOS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PodOS{}

// V1PodOS PodOS defines the OS parameters of a pod.
type V1PodOS struct {
	// Name is the name of the operating system. The currently supported values are linux and windows. Additional value may be defined in future and can be one of: https://github.com/opencontainers/runtime-spec/blob/master/config.md#platform-specific-configuration Clients should expect to handle additional values and treat unrecognized values in this field as os: null
	Name string `json:"name"`
}

type _V1PodOS V1PodOS

// NewV1PodOS instantiates a new V1PodOS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PodOS(name string) *V1PodOS {
	this := V1PodOS{}
	this.Name = name
	return &this
}

// NewV1PodOSWithDefaults instantiates a new V1PodOS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PodOSWithDefaults() *V1PodOS {
	this := V1PodOS{}
	return &this
}

// GetName returns the Name field value
func (o *V1PodOS) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1PodOS) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1PodOS) SetName(v string) {
	o.Name = v
}

func (o V1PodOS) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PodOS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *V1PodOS) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1PodOS := _V1PodOS{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1PodOS)

	if err != nil {
		return err
	}

	*o = V1PodOS(varV1PodOS)

	return err
}

type NullableV1PodOS struct {
	value *V1PodOS
	isSet bool
}

func (v NullableV1PodOS) Get() *V1PodOS {
	return v.value
}

func (v *NullableV1PodOS) Set(val *V1PodOS) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PodOS) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PodOS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PodOS(val *V1PodOS) *NullableV1PodOS {
	return &NullableV1PodOS{value: val, isSet: true}
}

func (v NullableV1PodOS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PodOS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


