/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OpenpitrixCreateCategoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenpitrixCreateCategoryResponse{}

// OpenpitrixCreateCategoryResponse struct for OpenpitrixCreateCategoryResponse
type OpenpitrixCreateCategoryResponse struct {
	CategoryId *string `json:"category_id,omitempty"`
}

// NewOpenpitrixCreateCategoryResponse instantiates a new OpenpitrixCreateCategoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenpitrixCreateCategoryResponse() *OpenpitrixCreateCategoryResponse {
	this := OpenpitrixCreateCategoryResponse{}
	return &this
}

// NewOpenpitrixCreateCategoryResponseWithDefaults instantiates a new OpenpitrixCreateCategoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenpitrixCreateCategoryResponseWithDefaults() *OpenpitrixCreateCategoryResponse {
	this := OpenpitrixCreateCategoryResponse{}
	return &this
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *OpenpitrixCreateCategoryResponse) GetCategoryId() string {
	if o == nil || IsNil(o.CategoryId) {
		var ret string
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenpitrixCreateCategoryResponse) GetCategoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryId) {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *OpenpitrixCreateCategoryResponse) HasCategoryId() bool {
	if o != nil && !IsNil(o.CategoryId) {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *OpenpitrixCreateCategoryResponse) SetCategoryId(v string) {
	o.CategoryId = &v
}

func (o OpenpitrixCreateCategoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenpitrixCreateCategoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CategoryId) {
		toSerialize["category_id"] = o.CategoryId
	}
	return toSerialize, nil
}

type NullableOpenpitrixCreateCategoryResponse struct {
	value *OpenpitrixCreateCategoryResponse
	isSet bool
}

func (v NullableOpenpitrixCreateCategoryResponse) Get() *OpenpitrixCreateCategoryResponse {
	return v.value
}

func (v *NullableOpenpitrixCreateCategoryResponse) Set(val *OpenpitrixCreateCategoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenpitrixCreateCategoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenpitrixCreateCategoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenpitrixCreateCategoryResponse(val *OpenpitrixCreateCategoryResponse) *NullableOpenpitrixCreateCategoryResponse {
	return &NullableOpenpitrixCreateCategoryResponse{value: val, isSet: true}
}

func (v NullableOpenpitrixCreateCategoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenpitrixCreateCategoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


