/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1alpha2TopologyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha2TopologyResponse{}

// V1alpha2TopologyResponse struct for V1alpha2TopologyResponse
type V1alpha2TopologyResponse struct {
	Nodes map[string]V1alpha2NodeSummary `json:"nodes"`
}

type _V1alpha2TopologyResponse V1alpha2TopologyResponse

// NewV1alpha2TopologyResponse instantiates a new V1alpha2TopologyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha2TopologyResponse(nodes map[string]V1alpha2NodeSummary) *V1alpha2TopologyResponse {
	this := V1alpha2TopologyResponse{}
	this.Nodes = nodes
	return &this
}

// NewV1alpha2TopologyResponseWithDefaults instantiates a new V1alpha2TopologyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha2TopologyResponseWithDefaults() *V1alpha2TopologyResponse {
	this := V1alpha2TopologyResponse{}
	return &this
}

// GetNodes returns the Nodes field value
func (o *V1alpha2TopologyResponse) GetNodes() map[string]V1alpha2NodeSummary {
	if o == nil {
		var ret map[string]V1alpha2NodeSummary
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *V1alpha2TopologyResponse) GetNodesOk() (*map[string]V1alpha2NodeSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nodes, true
}

// SetNodes sets field value
func (o *V1alpha2TopologyResponse) SetNodes(v map[string]V1alpha2NodeSummary) {
	o.Nodes = v
}

func (o V1alpha2TopologyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha2TopologyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodes"] = o.Nodes
	return toSerialize, nil
}

func (o *V1alpha2TopologyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nodes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1alpha2TopologyResponse := _V1alpha2TopologyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1alpha2TopologyResponse)

	if err != nil {
		return err
	}

	*o = V1alpha2TopologyResponse(varV1alpha2TopologyResponse)

	return err
}

type NullableV1alpha2TopologyResponse struct {
	value *V1alpha2TopologyResponse
	isSet bool
}

func (v NullableV1alpha2TopologyResponse) Get() *V1alpha2TopologyResponse {
	return v.value
}

func (v *NullableV1alpha2TopologyResponse) Set(val *V1alpha2TopologyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha2TopologyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha2TopologyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha2TopologyResponse(val *V1alpha2TopologyResponse) *NullableV1alpha2TopologyResponse {
	return &NullableV1alpha2TopologyResponse{value: val, isSet: true}
}

func (v NullableV1alpha2TopologyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha2TopologyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


