/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1alpha2NodeSummaryGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha2NodeSummaryGroup{}

// V1alpha2NodeSummaryGroup struct for V1alpha2NodeSummaryGroup
type V1alpha2NodeSummaryGroup struct {
	Columns []V1alpha2Column `json:"columns"`
	Id string `json:"id"`
	Label string `json:"label"`
	Nodes []V1alpha2NodeSummary `json:"nodes"`
	TopologyId string `json:"topologyId"`
}

type _V1alpha2NodeSummaryGroup V1alpha2NodeSummaryGroup

// NewV1alpha2NodeSummaryGroup instantiates a new V1alpha2NodeSummaryGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha2NodeSummaryGroup(columns []V1alpha2Column, id string, label string, nodes []V1alpha2NodeSummary, topologyId string) *V1alpha2NodeSummaryGroup {
	this := V1alpha2NodeSummaryGroup{}
	this.Columns = columns
	this.Id = id
	this.Label = label
	this.Nodes = nodes
	this.TopologyId = topologyId
	return &this
}

// NewV1alpha2NodeSummaryGroupWithDefaults instantiates a new V1alpha2NodeSummaryGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha2NodeSummaryGroupWithDefaults() *V1alpha2NodeSummaryGroup {
	this := V1alpha2NodeSummaryGroup{}
	return &this
}

// GetColumns returns the Columns field value
func (o *V1alpha2NodeSummaryGroup) GetColumns() []V1alpha2Column {
	if o == nil {
		var ret []V1alpha2Column
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *V1alpha2NodeSummaryGroup) GetColumnsOk() ([]V1alpha2Column, bool) {
	if o == nil {
		return nil, false
	}
	return o.Columns, true
}

// SetColumns sets field value
func (o *V1alpha2NodeSummaryGroup) SetColumns(v []V1alpha2Column) {
	o.Columns = v
}

// GetId returns the Id field value
func (o *V1alpha2NodeSummaryGroup) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V1alpha2NodeSummaryGroup) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V1alpha2NodeSummaryGroup) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *V1alpha2NodeSummaryGroup) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *V1alpha2NodeSummaryGroup) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *V1alpha2NodeSummaryGroup) SetLabel(v string) {
	o.Label = v
}

// GetNodes returns the Nodes field value
func (o *V1alpha2NodeSummaryGroup) GetNodes() []V1alpha2NodeSummary {
	if o == nil {
		var ret []V1alpha2NodeSummary
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *V1alpha2NodeSummaryGroup) GetNodesOk() ([]V1alpha2NodeSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *V1alpha2NodeSummaryGroup) SetNodes(v []V1alpha2NodeSummary) {
	o.Nodes = v
}

// GetTopologyId returns the TopologyId field value
func (o *V1alpha2NodeSummaryGroup) GetTopologyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TopologyId
}

// GetTopologyIdOk returns a tuple with the TopologyId field value
// and a boolean to check if the value has been set.
func (o *V1alpha2NodeSummaryGroup) GetTopologyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TopologyId, true
}

// SetTopologyId sets field value
func (o *V1alpha2NodeSummaryGroup) SetTopologyId(v string) {
	o.TopologyId = v
}

func (o V1alpha2NodeSummaryGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha2NodeSummaryGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["columns"] = o.Columns
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["nodes"] = o.Nodes
	toSerialize["topologyId"] = o.TopologyId
	return toSerialize, nil
}

func (o *V1alpha2NodeSummaryGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"columns",
		"id",
		"label",
		"nodes",
		"topologyId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1alpha2NodeSummaryGroup := _V1alpha2NodeSummaryGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1alpha2NodeSummaryGroup)

	if err != nil {
		return err
	}

	*o = V1alpha2NodeSummaryGroup(varV1alpha2NodeSummaryGroup)

	return err
}

type NullableV1alpha2NodeSummaryGroup struct {
	value *V1alpha2NodeSummaryGroup
	isSet bool
}

func (v NullableV1alpha2NodeSummaryGroup) Get() *V1alpha2NodeSummaryGroup {
	return v.value
}

func (v *NullableV1alpha2NodeSummaryGroup) Set(val *V1alpha2NodeSummaryGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha2NodeSummaryGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha2NodeSummaryGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha2NodeSummaryGroup(val *V1alpha2NodeSummaryGroup) *NullableV1alpha2NodeSummaryGroup {
	return &NullableV1alpha2NodeSummaryGroup{value: val, isSet: true}
}

func (v NullableV1alpha2NodeSummaryGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha2NodeSummaryGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


