/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1PersistentVolumeClaimVolumeSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PersistentVolumeClaimVolumeSource{}

// V1PersistentVolumeClaimVolumeSource PersistentVolumeClaimVolumeSource references the user's PVC in the same namespace. This volume finds the bound PV and mounts that volume for the pod. A PersistentVolumeClaimVolumeSource is, essentially, a wrapper around another type of volume that is owned by someone else (the system).
type V1PersistentVolumeClaimVolumeSource struct {
	// ClaimName is the name of a PersistentVolumeClaim in the same namespace as the pod using this volume. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims
	ClaimName string `json:"claimName"`
	// Will force the ReadOnly setting in VolumeMounts. Default false.
	ReadOnly *bool `json:"readOnly,omitempty"`
}

type _V1PersistentVolumeClaimVolumeSource V1PersistentVolumeClaimVolumeSource

// NewV1PersistentVolumeClaimVolumeSource instantiates a new V1PersistentVolumeClaimVolumeSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PersistentVolumeClaimVolumeSource(claimName string) *V1PersistentVolumeClaimVolumeSource {
	this := V1PersistentVolumeClaimVolumeSource{}
	this.ClaimName = claimName
	return &this
}

// NewV1PersistentVolumeClaimVolumeSourceWithDefaults instantiates a new V1PersistentVolumeClaimVolumeSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PersistentVolumeClaimVolumeSourceWithDefaults() *V1PersistentVolumeClaimVolumeSource {
	this := V1PersistentVolumeClaimVolumeSource{}
	return &this
}

// GetClaimName returns the ClaimName field value
func (o *V1PersistentVolumeClaimVolumeSource) GetClaimName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClaimName
}

// GetClaimNameOk returns a tuple with the ClaimName field value
// and a boolean to check if the value has been set.
func (o *V1PersistentVolumeClaimVolumeSource) GetClaimNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimName, true
}

// SetClaimName sets field value
func (o *V1PersistentVolumeClaimVolumeSource) SetClaimName(v string) {
	o.ClaimName = v
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise.
func (o *V1PersistentVolumeClaimVolumeSource) GetReadOnly() bool {
	if o == nil || IsNil(o.ReadOnly) {
		var ret bool
		return ret
	}
	return *o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PersistentVolumeClaimVolumeSource) GetReadOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.ReadOnly) {
		return nil, false
	}
	return o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *V1PersistentVolumeClaimVolumeSource) HasReadOnly() bool {
	if o != nil && !IsNil(o.ReadOnly) {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given bool and assigns it to the ReadOnly field.
func (o *V1PersistentVolumeClaimVolumeSource) SetReadOnly(v bool) {
	o.ReadOnly = &v
}

func (o V1PersistentVolumeClaimVolumeSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PersistentVolumeClaimVolumeSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["claimName"] = o.ClaimName
	if !IsNil(o.ReadOnly) {
		toSerialize["readOnly"] = o.ReadOnly
	}
	return toSerialize, nil
}

func (o *V1PersistentVolumeClaimVolumeSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"claimName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1PersistentVolumeClaimVolumeSource := _V1PersistentVolumeClaimVolumeSource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1PersistentVolumeClaimVolumeSource)

	if err != nil {
		return err
	}

	*o = V1PersistentVolumeClaimVolumeSource(varV1PersistentVolumeClaimVolumeSource)

	return err
}

type NullableV1PersistentVolumeClaimVolumeSource struct {
	value *V1PersistentVolumeClaimVolumeSource
	isSet bool
}

func (v NullableV1PersistentVolumeClaimVolumeSource) Get() *V1PersistentVolumeClaimVolumeSource {
	return v.value
}

func (v *NullableV1PersistentVolumeClaimVolumeSource) Set(val *V1PersistentVolumeClaimVolumeSource) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PersistentVolumeClaimVolumeSource) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PersistentVolumeClaimVolumeSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PersistentVolumeClaimVolumeSource(val *V1PersistentVolumeClaimVolumeSource) *NullableV1PersistentVolumeClaimVolumeSource {
	return &NullableV1PersistentVolumeClaimVolumeSource{value: val, isSet: true}
}

func (v NullableV1PersistentVolumeClaimVolumeSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PersistentVolumeClaimVolumeSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


