/*
KS API

KubeSphere OpenAPI

API version: v4.1.1
Contact: support@kubesphere.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1alpha1ClusterCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1ClusterCondition{}

// V1alpha1ClusterCondition struct for V1alpha1ClusterCondition
type V1alpha1ClusterCondition struct {
	LastTransitionTime *string `json:"lastTransitionTime,omitempty"`
	LastUpdateTime *string `json:"lastUpdateTime,omitempty"`
	Message *string `json:"message,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Status string `json:"status"`
	Type string `json:"type"`
}

type _V1alpha1ClusterCondition V1alpha1ClusterCondition

// NewV1alpha1ClusterCondition instantiates a new V1alpha1ClusterCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1ClusterCondition(status string, type_ string) *V1alpha1ClusterCondition {
	this := V1alpha1ClusterCondition{}
	this.Status = status
	this.Type = type_
	return &this
}

// NewV1alpha1ClusterConditionWithDefaults instantiates a new V1alpha1ClusterCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1ClusterConditionWithDefaults() *V1alpha1ClusterCondition {
	this := V1alpha1ClusterCondition{}
	return &this
}

// GetLastTransitionTime returns the LastTransitionTime field value if set, zero value otherwise.
func (o *V1alpha1ClusterCondition) GetLastTransitionTime() string {
	if o == nil || IsNil(o.LastTransitionTime) {
		var ret string
		return ret
	}
	return *o.LastTransitionTime
}

// GetLastTransitionTimeOk returns a tuple with the LastTransitionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ClusterCondition) GetLastTransitionTimeOk() (*string, bool) {
	if o == nil || IsNil(o.LastTransitionTime) {
		return nil, false
	}
	return o.LastTransitionTime, true
}

// HasLastTransitionTime returns a boolean if a field has been set.
func (o *V1alpha1ClusterCondition) HasLastTransitionTime() bool {
	if o != nil && !IsNil(o.LastTransitionTime) {
		return true
	}

	return false
}

// SetLastTransitionTime gets a reference to the given string and assigns it to the LastTransitionTime field.
func (o *V1alpha1ClusterCondition) SetLastTransitionTime(v string) {
	o.LastTransitionTime = &v
}

// GetLastUpdateTime returns the LastUpdateTime field value if set, zero value otherwise.
func (o *V1alpha1ClusterCondition) GetLastUpdateTime() string {
	if o == nil || IsNil(o.LastUpdateTime) {
		var ret string
		return ret
	}
	return *o.LastUpdateTime
}

// GetLastUpdateTimeOk returns a tuple with the LastUpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ClusterCondition) GetLastUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdateTime) {
		return nil, false
	}
	return o.LastUpdateTime, true
}

// HasLastUpdateTime returns a boolean if a field has been set.
func (o *V1alpha1ClusterCondition) HasLastUpdateTime() bool {
	if o != nil && !IsNil(o.LastUpdateTime) {
		return true
	}

	return false
}

// SetLastUpdateTime gets a reference to the given string and assigns it to the LastUpdateTime field.
func (o *V1alpha1ClusterCondition) SetLastUpdateTime(v string) {
	o.LastUpdateTime = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V1alpha1ClusterCondition) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ClusterCondition) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V1alpha1ClusterCondition) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V1alpha1ClusterCondition) SetMessage(v string) {
	o.Message = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *V1alpha1ClusterCondition) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1ClusterCondition) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *V1alpha1ClusterCondition) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *V1alpha1ClusterCondition) SetReason(v string) {
	o.Reason = &v
}

// GetStatus returns the Status field value
func (o *V1alpha1ClusterCondition) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V1alpha1ClusterCondition) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V1alpha1ClusterCondition) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *V1alpha1ClusterCondition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V1alpha1ClusterCondition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V1alpha1ClusterCondition) SetType(v string) {
	o.Type = v
}

func (o V1alpha1ClusterCondition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1ClusterCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastTransitionTime) {
		toSerialize["lastTransitionTime"] = o.LastTransitionTime
	}
	if !IsNil(o.LastUpdateTime) {
		toSerialize["lastUpdateTime"] = o.LastUpdateTime
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	toSerialize["status"] = o.Status
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *V1alpha1ClusterCondition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1alpha1ClusterCondition := _V1alpha1ClusterCondition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1alpha1ClusterCondition)

	if err != nil {
		return err
	}

	*o = V1alpha1ClusterCondition(varV1alpha1ClusterCondition)

	return err
}

type NullableV1alpha1ClusterCondition struct {
	value *V1alpha1ClusterCondition
	isSet bool
}

func (v NullableV1alpha1ClusterCondition) Get() *V1alpha1ClusterCondition {
	return v.value
}

func (v *NullableV1alpha1ClusterCondition) Set(val *V1alpha1ClusterCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1ClusterCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1ClusterCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1ClusterCondition(val *V1alpha1ClusterCondition) *NullableV1alpha1ClusterCondition {
	return &NullableV1alpha1ClusterCondition{value: val, isSet: true}
}

func (v NullableV1alpha1ClusterCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1ClusterCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


