/*
KubeSphere

KubeSphere OpenAPI

API version: v3.1.0
Contact: info@kubesphere.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1alpha2NodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha2NodeResponse{}

// V1alpha2NodeResponse struct for V1alpha2NodeResponse
type V1alpha2NodeResponse struct {
	Node V1alpha2Node `json:"node"`
}

type _V1alpha2NodeResponse V1alpha2NodeResponse

// NewV1alpha2NodeResponse instantiates a new V1alpha2NodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha2NodeResponse(node V1alpha2Node) *V1alpha2NodeResponse {
	this := V1alpha2NodeResponse{}
	this.Node = node
	return &this
}

// NewV1alpha2NodeResponseWithDefaults instantiates a new V1alpha2NodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha2NodeResponseWithDefaults() *V1alpha2NodeResponse {
	this := V1alpha2NodeResponse{}
	return &this
}

// GetNode returns the Node field value
func (o *V1alpha2NodeResponse) GetNode() V1alpha2Node {
	if o == nil {
		var ret V1alpha2Node
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *V1alpha2NodeResponse) GetNodeOk() (*V1alpha2Node, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *V1alpha2NodeResponse) SetNode(v V1alpha2Node) {
	o.Node = v
}

func (o V1alpha2NodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha2NodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node"] = o.Node
	return toSerialize, nil
}

func (o *V1alpha2NodeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1alpha2NodeResponse := _V1alpha2NodeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1alpha2NodeResponse)

	if err != nil {
		return err
	}

	*o = V1alpha2NodeResponse(varV1alpha2NodeResponse)

	return err
}

type NullableV1alpha2NodeResponse struct {
	value *V1alpha2NodeResponse
	isSet bool
}

func (v NullableV1alpha2NodeResponse) Get() *V1alpha2NodeResponse {
	return v.value
}

func (v *NullableV1alpha2NodeResponse) Set(val *V1alpha2NodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha2NodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha2NodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha2NodeResponse(val *V1alpha2NodeResponse) *NullableV1alpha2NodeResponse {
	return &NullableV1alpha2NodeResponse{value: val, isSet: true}
}

func (v NullableV1alpha2NodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha2NodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


